### ISSUE TITLE
Support for nvim-tree.lua

### ISSUE THREAD

**Issue by gegoune** [ygm2/rooter.nvim#2]
Would you consider adding support for [kyazdani42/nvim-tree.lua](https://github.com/kyazdani42/nvim-tree.lua) plugin, so if it is installed it it would call function like [this](https://github.com/ahmedkhalf/lsp-rooter.nvim/blob/ca8670c8fc4efbd9a05f330f4037304962c9abbb/lua/lsp-rooter/rooter.lua#L5) to update its directory as well?

**Comment by AkashKarnatak** [comment]
If thou shalt ask, thou shalt receive :) d5d62e86

**Comment by ygm2** [comment]
5d62e86
