### ISSUE TITLE
change directory to directory of current file if root marker is not found

### ISSUE THREAD

**Issue by dchinmay2** [ygm2/rooter.nvim#5]
If a matching root marker is not found, can you add an option to change cwd to the parent of the current file?

**Comment by AlixShahid** [comment]
@p00f implemented this on my new plugin, [penvim](https://github.com/shaeinst/penvim)

**Comment by dchinmay2** [comment]
Nice, but I think changing pwd for everything creates more problems than it solves (fugitive, man etc misbehave)

**Comment by AlixShahid** [comment]
problems like?
